name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  JAVA_VERSION: "17"
  JAVA_DISTRIBUTION: "temurin"
  API_LEVEL: "31"
  TARGET: "google_apis"
  ARCH: "x86_64"
  CMD_TIMEOUT: "600"

jobs:
  lint:
    name: Run Lint Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint check
        run: ./gradlew ktlintCheck

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: gradle

      - name: Create local.properties
        run: |
          echo "OPENWEATHER_API_KEY_DEBUG=${{ secrets.OPENWEATHER_API_KEY_DEBUG }}" > local.properties
          echo "OPENWEATHER_API_KEY_RELEASE=${{ secrets.OPENWEATHER_API_KEY_RELEASE }}" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew test -x :app:testDebugUnitTest -x :app:testReleaseUnitTest

  ui-test:
    name: Run UI Tests
    runs-on: macos-13
    needs: lint
    timeout-minutes: 60
    env:
      ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 120
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: gradle

      - name: Create local.properties
        run: |
          echo "OPENWEATHER_API_KEY_DEBUG=${{ secrets.OPENWEATHER_API_KEY_DEBUG }}" > local.properties
          echo "OPENWEATHER_API_KEY_RELEASE=${{ secrets.OPENWEATHER_API_KEY_RELEASE }}" >> local.properties

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK Components
        run: |
          sdkmanager --install \
            "build-tools;34.0.0" \
            "platform-tools" \
            "platforms;android-31" \
            "emulator" \
            "system-images;android-31;google_apis;x86_64"

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses || true

      - name: Create AVD and modify config
        run: |
          echo "no" | avdmanager create avd \
            --force \
            --name "test_device" \
            --package "system-images;android-31;google_apis;x86_64" \
            --device "pixel_6"

          echo "hw.cpu.ncore=1" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.ramSize=2048" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.lcd.density=440" >> ~/.android/avd/test_device.avd/config.ini
          echo "disk.dataPartition.size=2048M" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.keyboard=yes" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.gpu.enabled=yes" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.gpu.mode=swiftshader_indirect" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.audioInput=no" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.audioOutput=no" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.camera.back=none" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.camera.front=none" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.arc=false" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.sensors.proximity=no" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.sensors.magnetic_field=no" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.sensors.orientation=no" >> ~/.android/avd/test_device.avd/config.ini
          echo "hw.sensors.temperature=no" >> ~/.android/avd/test_device.avd/config.ini

      - name: Configure ADB
        run: |
          adb kill-server || true
          sleep 5
          adb start-server
          adb devices

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          target: ${{ env.TARGET }}
          arch: ${{ env.ARCH }}
          avd-name: test_device
          force-avd-creation: false
          emulator-boot-timeout: 1200
          disable-animations: true
          disable-spellchecker: true
          emulator-options: >-
            -no-snapshot-save
            -no-window
            -gpu swiftshader_indirect
            -noaudio
            -no-boot-anim
            -camera-back none
            -no-snapshot
            -memory 2048
            -no-accel
            -cores 1
            -no-audio
          script: |
            # Kill and restart ADB to ensure clean state
            adb kill-server || true
            sleep 5
            adb start-server

            # Wait for emulator to start with increased timeout
            adb wait-for-device
            sleep 10

            # More robust boot completion check with longer timeout
            timeout=1200
            start_time=$(date +%s)
            bootanim=""

            until [[ "$(adb shell getprop sys.boot_completed 2>&1)" == "1" ]] || [[ "$(adb shell getprop dev.bootcomplete 2>&1)" == "1" ]]; do
              current_time=$(date +%s)
              elapsed=$((current_time - start_time))
              
              if [[ $elapsed -ge $timeout ]]; then
                echo "Timeout waiting for boot completion"
                exit 1
              fi
              
              echo "Waiting for boot completion... (${elapsed}s)"
              adb devices
              bootanim=$(adb shell getprop init.svc.bootanim 2>&1 || echo "unknown")
              echo "Boot animation status: $bootanim"
              sleep 10
            done

            # Additional boot verification
            adb shell input keyevent 82
            sleep 5

            # Disable animations
            adb shell settings put global window_animation_scale 0.0
            adb shell settings put global transition_animation_scale 0.0
            adb shell settings put global animator_duration_scale 0.0

            # Start logcat capture
            adb logcat > emulator.log &

            # Run tests with retry mechanism
            max_retries=3
            for ((i=1; i<=max_retries; i++)); do
              echo "Test attempt $i of $max_retries"
              
              # Check device state before running tests
              adb devices
              adb shell getprop sys.boot_completed
              
              if ./gradlew connectedCheck --debug; then
                echo "Tests completed successfully"
                exit 0
              else
                echo "Attempt $i failed"
                if [[ $i -lt $max_retries ]]; then
                  echo "Waiting before retry..."
                  adb devices
                  sleep 30
                fi
              fi
            done

            echo "All test attempts failed"
            exit 1

      - name: Upload UI Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: |
            app/build/reports/androidTests/
            emulator.log

  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    needs: [test, ui-test]
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: gradle

      - name: Create local.properties
        run: |
          echo "OPENWEATHER_API_KEY_DEBUG=${{ secrets.OPENWEATHER_API_KEY_DEBUG }}" > local.properties
          echo "OPENWEATHER_API_KEY_RELEASE=${{ secrets.OPENWEATHER_API_KEY_RELEASE }}" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Build Release Bundle
    runs-on: ubuntu-latest
    needs: [test, ui-test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: gradle

      - name: Create local.properties
        run: |
          echo "OPENWEATHER_API_KEY_DEBUG=${{ secrets.OPENWEATHER_API_KEY_DEBUG }}" > local.properties
          echo "OPENWEATHER_API_KEY_RELEASE=${{ secrets.OPENWEATHER_API_KEY_RELEASE }}" >> local.properties

      - name: Setup Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > bestbikeday.keystore

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      - name: Upload Release Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/bundle/release/app-release.aab
