name: Android CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Add repository-level permissions
permissions:
  contents: write
  packages: read
  actions: write
  checks: write
  pull-requests: write

env:
  JAVA_VERSION: "17"
  JAVA_DISTRIBUTION: "temurin"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create keystore.properties
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY_DEBUG }}
        run: |
          echo "OPENWEATHER_API_KEY_DEBUG=$OPENWEATHER_API_KEY" > keystore.properties
          echo "OPENWEATHER_API_KEY_RELEASE=$OPENWEATHER_API_KEY" >> keystore.properties
          cat keystore.properties

      - name: Build Debug APK
        run: ./gradlew assembleDebug --info --stacktrace

      - name: List build outputs
        run: |
          echo "Listing build outputs directory:"
          ls -R app/build/outputs/

      - name: Upload Debug APK
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 5

      - name: Upload Build Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: app/build/reports/
