name: Android Release Build

on:
  push:
    tags:
      - "v*" # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_FILE }}
        run: |
          echo $ENCODED_KEYSTORE | base64 -d > bestbikeday.keystore

      - name: Create keystore.properties
        env:
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY_RELEASE }}
        run: |
          echo "storePassword=$STORE_PASSWORD" > keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
          echo "keyAlias=$KEY_ALIAS" >> keystore.properties
          echo "storeFile=bestbikeday.keystore" >> keystore.properties
          echo "OPENWEATHER_API_KEY_DEBUG=$OPENWEATHER_API_KEY" >> keystore.properties
          echo "OPENWEATHER_API_KEY_RELEASE=$OPENWEATHER_API_KEY" >> keystore.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release Bundle
        run: ./gradlew clean bundleRelease

      - name: Upload Release Bundle
        uses: actions/upload-artifact@v3
        with:
          name: release-bundle
          path: app/build/outputs/bundle/release/app-release.aab
